### ISSUE TITLE
NoMethodError view_namespace=

### ISSUE THREAD

**Issue by kingdonb** [mustache/mustache-sinatra#1]
I'm unable to start the example code.

```
NoMethodError at /
undefined method `view_namespace=' for #<Class:0x007f791c509c80>
file: sinatra.rb location: block in compile_mustache line: 95
```

I found out that sinatra needs an update for Rack 1.6 that still hasn't made it into a release, so I pinned Rack at `'< 1.6'`

I have a working example app from Mustache 0.99.4 with some Gemfile resources locked, not sure what else might have changed, but I am pretty sure I shouldn't need to require all of these view classes by hand or do any weird hacks like `$:<<'./'`

I posted at [kingdonb/mustache-sinatra-example#07532cdd](https://github.com/kingdonb/mustache-sinatra-example/commit/07532cdd007a841f982e3634a12e836bab0a1921) my working example from that older version.

The next commit shows a fresh `Gemfile.lock` after deleting it and running `bundle update`, with the new `gem 'mustache-sinatra'`, I get the undefined method `view_namespace=`.  I don't know why this doesn't work.  Tried with several versions of ruby.  Maybe I'm using it wrong.

**Comment by kingdonb** [comment]
This happens when you fail to `require 'mustache'`.  Sorry.

Closing.

**Comment by locks** [comment]
Hm, I should probably `require 'mustache'` in my extension. That would mean specifying which version of `mustache` the extension supports, which isn't a bad idea either.
Thanks for the report, it'll prove useful.

**Comment by locks** [comment]
@kingdonb released `v1.0.1` which hopefully fixes this :)

**Comment by kingdonb** [comment]
Great :D  Do you think it should set up a particular version of sinatra, too?

I tried to reproduce my issue with sinatra and rack but could not immediately cause a failure in the same way (something related to the version of rack and last sinatra release, that was apparently fixed in git head at that time last week but not yet in a release.)

So, I'd say everything is fine

**Comment by locks** [comment]
Hm, specifying a Sinatra version might be trickier. It should work as long as it's in the 1.x branch, no?
If you make a PR for it I would accept it however, I just don't know what is/should be supported.

Thank you for confirming :)

**Comment by kingdonb** [comment]
Same here, I am not an expert on different versions of Sinatra (I don't even play one on TV)

**Comment by locks** [comment]
We'll leave it at that then, until said expert comes along ;)
