### ISSUE TITLE
Depend on newer mustache for Ruby 3.2 compatibilty

### ISSUE THREAD

**Issue by dometto** [mustache/mustache-sinatra#10]
Until now `mustache-sinatra` has been working fine despite depending on an older version of `mustache` (<= 1.00). However, that version of mustache is sadly no longer compatible with Ruby v3.2. Is anyone still maintaining this library, and how much work would it be to cut a new gem release depending on a newer mustache version?

**Comment by dometto** [comment]
NB: it looks like this has already been done on `master`, but this change has never been released. Since the build seems to be passing, can someone please do a quick `gem release`? Many thanks!

**Comment by dometto** [comment]
Pinging @ThijsWouters :)

**Comment by dometto** [comment]
Ping @locks! Any chance you could release a new version of this gem? I would happily create a PR to update mustache.

**Comment by locks** [comment]
Thanks for the ping, I have been away and the missed this issue originally. I'll be doing a release today!

**Comment by locks** [comment]
@dometto v1.0.2 is out https://rubygems.org/gems/mustache-sinatra. Can you do a quick check and let me know if there's a problem?

**Comment by alzeih** [comment]
I get an error with gollum and mustache-sinatra 1.0.2 

> NoMethodError private method `escape` called for <<Precious::Views::Create: ...

I encountered this error right after installing gollum today for a brand new instance.  It occurred on visiting `http://localhost:4567` for an empty wiki.


Downgrading to mustache-sinatra 1.0.1 fixes it for me.

**Comment by dometto** [comment]
Thanks for the new release @locks!

@alzeih yes, unfortunately, because the latest release of `mustache-siinatra` was a bump release, `gollum` automatically installs it, and is thereby exposed to breaking changes in the latest version of mustache. I'm addressing this issue as we speak.

**Comment by locks** [comment]
> Thanks for the new release @locks!
> 
> @alzeih yes, unfortunately, because the latest release of `mustache-siinatra` was a bump release, `gollum` automatically installs it, and is thereby exposed to breaking changes in the latest version of mustache. I'm addressing this issue as we speak.

If you need anything from mustache-sinatra to make it easier let me know and I can merge.

**Comment by dometto** [comment]
Thanks @locks, I think I have everything covered now.

@alzeih: https://github.com/gollum/gollum/pull/1954 for reference.

**Comment by locks** [comment]
@dometto I've re-published as 2.0.0 and I will be yanking 1.0.2 so gollum and other users don't run into the same problem. Sorry for the poor release, it's been a while!

**Comment by dometto** [comment]
No worries, we've all been there! Also I would have had to address the incompatibilities anyway, so no time lost. :) Thanks again for taking care of this!

**Comment by alzeih** [comment]
Yes, I just picked the wrong moment to start a new wiki! 

I posted in case anyone else encountered this error and was as confused as I was.

Thank you both for the rapid response.
