### ISSUE TITLE
First call to mustache fails to lookup the view class when using the default options

### ISSUE THREAD

**Issue by ThijsWouters** [mustache/mustache-sinatra#2]
When I have [this program](https://gist.github.com/ThijsWouters/4d47175e5997a637d271), the first get to `/` fails to lookup the view. This is also in the log.

All subsequent calls load the view correctly.

**Comment by ThijsWouters** [comment]
I traced the bug back to [this line](https://github.com/mustache/mustache-sinatra/blob/master/lib/mustache/sinatra/helpers.rb#L91).

**Comment by ThijsWouters** [comment]
https://github.com/mustache/mustache-sinatra/pull/3

**Comment by ThijsWouters** [comment]
I provided a fix for you: https://github.com/mustache/mustache-sinatra/pull/3

**Comment by locks** [comment]
Merged. Appreciated :)

**Comment by locks** [comment]
Since you're using this gem, is there any possibility you could add some tests?
I could then setup Travis and have it publish new versions more easily.

**Comment by ThijsWouters** [comment]
I was thinking about doing that. I will take a look at it when I have some
time.

Met vriendelijke groeten,
Thijs Wouters.

2015-03-19 16:38 GMT+01:00 Ricardo Mendes notifications@github.com:
